id: "20260120-135420_browser"
title: "Browser"
created_at: "2026-01-20T13:54:20-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "606af857-cc7e-43bb-8111-2b256afad9bb"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
