id: "20260120-142537_update-voice-ids-configuration"
title: "Update voice IDs configuration"
created_at: "2026-01-20T14:25:37-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "ab13ebb5-719d-4a0d-853c-c1c983f9ad5d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
