id: "20260121-073123_synced"
title: "synced"
created_at: "2026-01-21T07:31:23-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "a7110e4b-3949-43b7-9dec-71b4f00b270d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
