id: "20260121-104636_why-is-the-voice-server-no-longer-workign"
title: "why is the voice server no longer workign?"
created_at: "2026-01-21T10:46:36-08:00"
completed_at: "2026-01-21T11:14:48-08:00"
source: "SESSION"
status: "COMPLETED"
session_id: "2ba5ce45-6955-43a0-8f7a-3e67f11cb2dd"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
