id: "20260120-133832_say-hi-with-your-voice"
title: "say hi with your voice"
created_at: "2026-01-20T13:38:32-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "e6dc6dfe-2f0a-4ce1-bafd-ccede6c62cb8"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
