id: "20260121-035231_replace-secondary-nav-acf-with-wordpress-menu"
title: "Replace secondary nav ACF with WordPress menu"
created_at: "2026-01-21T03:52:31-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "90f22534-fca1-42d6-9e5e-77fb9627669d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
