id: "20260121-025206_where-do-i-add-the-card-hub-heading"
title: "where do i add the card hub heading?"
created_at: "2026-01-21T02:52:06-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "90f22534-fca1-42d6-9e5e-77fb9627669d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
