id: "20260121-052455_sync-ghostty-keybindings-to-wezterm"
title: "Sync Ghostty keybindings to WezTerm"
created_at: "2026-01-21T05:24:55-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "1e54d29e-5ed9-43ee-be7e-0955be851e44"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
