id: "20260120-141327_so-the-other-voice-ids-are-hard-coded-into-voicese"
title: "so the other voice ids are hard coded into voicese"
created_at: "2026-01-20T14:13:27-08:00"
completed_at: "2026-01-20T14:14:29-08:00"
source: "SESSION"
status: "COMPLETED"
session_id: "ab13ebb5-719d-4a0d-853c-c1c983f9ad5d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
