id: "20260121-014133_update-secondary-nav-acf-field-for-internal-pages"
title: "Update secondary nav ACF field for internal pages"
created_at: "2026-01-21T01:41:33-08:00"
completed_at: "2026-01-21T01:45:51-08:00"
source: "SESSION"
status: "COMPLETED"
session_id: "90f22534-fca1-42d6-9e5e-77fb9627669d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
