id: "20260120-140103_when-we-set-the-voice-id-to-ioq2c1gjee5ryqeobih3-d"
title: "when we set the voice id to Ioq2c1GJee5RyqeoBIH3 d"
created_at: "2026-01-20T14:01:03-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "ab13ebb5-719d-4a0d-853c-c1c983f9ad5d"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
